spring:
  datasource:
    url: 'jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: root
    password: root
    driver-class-name: 'org.h2.Driver'
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true